# Generated by Django 4.2.10 on 2024-02-13 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel", "0010_roomcategory_rooms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default=None, max_length=64)),
                ("last_name", models.CharField(default=None, max_length=64)),
                ("email", models.CharField(default=None, max_length=64)),
                ("phone", models.CharField(default=None, max_length=64)),
                ("room", models.IntegerField(default=1)),
                ("person", models.IntegerField(default=1)),
                ("checkin_date", models.CharField(default=None, max_length=64)),
                ("checkout_date", models.CharField(default=None, max_length=64)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.CharField(default=None, max_length=64)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="hotel.hotel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
