# Generated by Django 4.2.10 on 2024-02-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="checkin_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="checkout_date",
            field=models.DateTimeField(),
        ),
    ]
