# Generated by Django 4.2.10 on 2024-02-13 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotel", "0010_roomcategory_rooms"),
        ("booking", "0004_alter_booking_checkin_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel.roomcategory",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
