# Generated by Django 4.2.10 on 2024-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_booking_room_category_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
