# Generated by Django 4.2.10 on 2024-03-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="checkin_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="checkout_date",
            field=models.DateField(),
        ),
    ]
