# Generated by Django 4.2.10 on 2024-03-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="booking.booking",
            ),
        ),
    ]
