# Generated by Django 4.2.10 on 2024-03-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_booking_first_name_alter_booking_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="last_name",
        ),
    ]
