# Generated by Django 4.2.10 on 2024-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_remove_booking_first_name_remove_booking_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
