# Generated by Django 4.2.10 on 2024-02-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="Image",
            new_name="image",
        ),
    ]
