# Generated by Django 3.2.2 on 2024-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rattings_delete_image_remove_hotel_rattings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='category_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Category Name'),
        ),
    ]
