# Generated by Django 4.2.10 on 2024-02-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_auto_20240212_0533"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomcategory",
            name="category_name",
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
    ]
