# Generated by Django 4.2.10 on 2024-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0009_roomcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcategory",
            name="rooms",
            field=models.IntegerField(null=True, verbose_name="Rooms"),
        ),
    ]
