# Generated by Django 4.2.10 on 2024-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0010_roomcategory_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="booked_rooms",
            field=models.TextField(null=True),
        ),
    ]
