# Generated by Django 4.2.10 on 2024-02-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0011_alter_hotel_booked_rooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="available_rooms",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="booked_rooms",
        ),
    ]
