# Generated by Django 4.2.10 on 2024-02-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0012_remove_hotel_available_rooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rattings",
            name="rattings",
            field=models.IntegerField(verbose_name="Rattings"),
        ),
    ]
