# Generated by Django 5.0.2 on 2024-03-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_hotelimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_category_images/')),
                ('Roomcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_category', to='hotel.roomcategory')),
            ],
        ),
    ]
