# Generated by Django 4.2.10 on 2024-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0018_remove_hotel_image_remove_roomcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="ratting",
            field=models.IntegerField(default=1, verbose_name="Ratting"),
            preserve_default=False,
        ),
    ]
