# Generated by Django 4.2.10 on 2024-03-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0019_hotel_ratting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="price",
        ),
    ]
