# Generated by Django 4.2.10 on 2024-03-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0020_remove_hotel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="ratting",
            field=models.IntegerField(null=True, verbose_name="Ratting"),
        ),
    ]
