# Generated by Django 4.2.10 on 2024-03-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0021_alter_hotel_ratting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="room",
        ),
    ]
